# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: http://files.joyofkosher.com/image/upload/MTMxNzYzNjQxOTM3NjIwOTYy.jpg

# Theme Main Subtitle
subtitle_main: Welcome to our amazing blog for fancy data vizZzZzZz

# Theme Secondary subtitle
susbtitle_secondary: (S)bread the numbers :)

# Footer About Section
about_footer: "Three extremely cool people #beprepared #russianDATAgangbang"

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://files.joyofkosher.com/image/upload/MTMxNzYzNjQxOTM3NjIwOTYy.jpg"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#
